# ============================================================================
# NEXUS BACKEND — Content API Routes
# ============================================================================
# Endpoints for viewing the content queue (social posts, email drafts).
#
# Content is generated by the Content Agent (Apollo) and queued here
# for organizer review before being published.
#
# Endpoint:
#   GET /api/content → Get the content queue
# ============================================================================

from typing import Optional
from fastapi import APIRouter

from app.state.state_manager import state_manager

# Create the router
router = APIRouter()


# ============================================================================
# GET /api/content — Get the content queue
# ============================================================================

@router.get("/content")
async def get_content(
    status: Optional[str] = None,
    content_type: Optional[str] = None,
    event_id: Optional[str] = None,
):
    """
    Get the current content queue.
    
    Returns all generated content pieces (social posts, email drafts,
    campaign items) with their status (draft, approved, published, rejected).
    
    Args:
        status: Filter by status (draft, approved, published, rejected)
        content_type: Filter by type (social_post, email_draft, campaign)
        event_id: Filter by event ID
    
    Returns:
        List of content items in the queue
    """
    # Try in-memory state first
    content_queue = state_manager.get_content_queue()

    if content_queue:
        # Apply filters if provided
        filtered = content_queue
        if status:
            filtered = [c for c in filtered if c.get("status") == status]
        if content_type:
            filtered = [c for c in filtered if c.get("content_type") == content_type]

        return {
            "status": "success",
            "content": filtered,
            "total": len(filtered),
        }

    # Fall back to database
    from app.database import get_db
    db = await get_db()

    # Build the query dynamically based on filters
    query = "SELECT * FROM content_queue WHERE 1=1"
    params = []

    if status:
        query += " AND status = ?"
        params.append(status)
    if content_type:
        query += " AND content_type = ?"
        params.append(content_type)
    if event_id:
        query += " AND event_id = ?"
        params.append(event_id)

    query += " ORDER BY created_at DESC"

    cursor = await db.execute(query, tuple(params))
    rows = await cursor.fetchall()
    content = [dict(row) for row in rows]

    return {
        "status": "success",
        "content": content,
        "total": len(content),
    }
