# ============================================================================
# NEXUS BACKEND — Content Pydantic Models
# ============================================================================
# These models define the inputs and outputs for Apollo (Content Agent).
# Apollo handles social media drafting, marketing campaigns, and 
# content sequencing.
# ============================================================================

from pydantic import BaseModel, Field
from typing import Optional, List, Literal


class ContentPiece(BaseModel):
    """
    Represents a single piece of generated content, like a Tweet, 
    LinkedIn post, or email header text.
    Stored in the content_queue table.
    """
    id: str = Field("", description="Unique identifier for the content piece")
    platform: str = Field("twitter", description="Target platform (twitter, linkedin, instagram, blog, email)")
    tone: str = Field("professional", description="The generated voice (professional, casual, hype, urgent)")
    text: str = Field(..., description="The actual copy generated by the LLM")
    hashtags: List[str] = Field(default_factory=list, description="List of generated hashtags")
    suggested_time: Optional[str] = Field(None, description="When Apollo thinks this should be posted")
    image_prompt: Optional[str] = Field(None, description="If applicable, a prompt for an image generator (like DALL-E/Midjourney)")
    status: str = Field("draft", description="State in the content queue (draft, approved, published, rejected)")


class CampaignPlan(BaseModel):
    """
    A sequential marketing plan generated by Apollo.
    Creates a timeline of multiple coordinated posts.
    """
    phases: List[str] = Field(default_factory=list, description="e.g., ['Teaser', 'Reveal', 'Countdown', 'D-Day', 'Recap']")
    total_posts: int = Field(0, description="Total number of content pieces in the campaign")
    duration_days: int = Field(7, description="How long the campaign runs for")


class EngagementAnalysis(BaseModel):
    """
    If historical data is provided, Apollo can analyze it to figure out
    the best times to post.
    """
    best_day: Optional[str] = Field(None, description="Day of the week with highest engagement")
    best_time: Optional[str] = Field(None, description="Time of day with highest engagement")
    top_content_type: Optional[str] = Field(None, description="Which style historically performs best")
    insights: List[str] = Field(default_factory=list, description="Natural language takeaways from the data")


class ContentRequest(BaseModel):
    """
    The structured input payload sent into the LangGraph orchestrator
    when targeting the Content Agent (Apollo).
    """
    action: Literal["generate", "plan_campaign", "analyze_timing", "update_content"] = Field(..., description="What Apollo should do")
    event_description: str = Field("", description="Context about the event Apollo is promoting")
    target_audience: Optional[str] = Field(None, description="Who the content should appeal to")
    tone: Optional[str] = Field("auto", description="Desired brand voice")
    platform: Optional[str] = Field(None, description="Specific platform constraint")
    historical_data: Optional[str] = Field(None, description="Data for Apollo to use for timing analysis")
    existing_content_id: Optional[str] = Field(None, description="ID if Apollo is editing an existing piece")


class ContentResult(BaseModel):
    """
    The structured output payload returned by Apollo.
    """
    content_pieces: List[ContentPiece] = Field(default_factory=list, description="The list of generated posts")
    campaign_timeline: Optional[CampaignPlan] = Field(None, description="The overarching structure if a campaign was requested")
    engagement_insights: Optional[EngagementAnalysis] = Field(None, description="Timing analysis if requested")
    reasoning: str = Field("", description="The AI's explanation of why it chose specific words/tones")
