import { useState } from 'react';
import { X, Download, FileText, Calendar, Users, DollarSign, BarChart, Loader2, CheckCircle, Clock, MapPin, Lock } from 'lucide-react';
import { getDashboard, getSessions, getParticipants, getActivity } from '../../services/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Color constants for PDF ──────────────────────────────────────
const BRAND = { r: 99, g: 102, b: 241 };          // Indigo primary
const DARK  = { r: 17, g: 17, b: 27 };            // Near-black bg
const GRAY  = { r: 156, g: 163, b: 175 };         // Text secondary
const WHITE = { r: 255, g: 255, b: 255 };

const EventBriefModal = ({ isOpen, onClose }) => {
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState('');
  const [done, setDone] = useState(false);

  // Section toggles
  const [includeSchedule, setIncludeSchedule] = useState(true);
  const [includeParticipants, setIncludeParticipants] = useState(true);
  const [includeActivity, setIncludeActivity] = useState(true);

  if (!isOpen) return null;

  const generatePDF = async () => {
    setGenerating(true);
    setDone(false);

    try {
      // ── Step 1: Fetch all data ──
      setProgress('Fetching event data...');
      const [dashboard, sessions, participants, activityRes] = await Promise.all([
        getDashboard().catch(() => null),
        getSessions().catch(() => []),
        getParticipants().catch(() => ({ participants: [] })),
        getActivity().catch(() => ({ activities: [] })),
      ]);

      const event = dashboard || {};
      const sessionList = Array.isArray(sessions) ? sessions : [];
      const participantList = participants?.participants || (Array.isArray(participants) ? participants : []);
      const activities = activityRes?.activities || [];

      // ── Step 2: Create PDF ──
      setProgress('Building PDF layout...');
      const doc = new jsPDF('p', 'mm', 'a4');
      const pw = doc.internal.pageSize.getWidth();
      const ph = doc.internal.pageSize.getHeight();
      let y = 0;

      // Helper: Format date manually (ASCII only to prevent encoding issues)
      const formatDate = (dateStr) => {
        if (!dateStr) return 'TBD';
        try {
          const d = new Date(dateStr);
          if (isNaN(d.getTime())) return dateStr;
          const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
          return `${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
        } catch { return dateStr; }
      };

      // Helper: Format current time manually (ASCII only)
      const formatTimeNow = () => {
        const d = new Date();
        const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        const formatNum = (n) => n.toString().padStart(2, '0');
        return `${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()} ${formatNum(d.getHours())}:${formatNum(d.getMinutes())}`;
      };

      // Helper: add footer to every page
      const addFooter = () => {
        const pages = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pages; i++) {
          doc.setPage(i);
          
          // Skip page 1 as it has a custom cover footer
          if (i === 1) continue;

          doc.setFontSize(7);
          doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
          doc.text(`Generated by NEXUS AI | ${formatTimeNow()}`, 14, ph - 8);
          doc.text(`Page ${i} of ${pages}`, pw - 14, ph - 8, { align: 'right' });
          
          // Top brand line
          doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
          doc.setLineWidth(1.5);
          doc.line(0, 0, pw, 0);
        }
      };

      // Helper: Add a content page with background
      const addContentPage = () => {
        doc.addPage();
        doc.setFillColor(22, 22, 32); // Darker gray for content pages
        doc.rect(0, 0, pw, ph, 'F');
      };

      // ════════════════════════════════════════════
      // COVER PAGE
      // ════════════════════════════════════════════
      setProgress('Generating cover page...');

      // Full dark background
      doc.setFillColor(DARK.r, DARK.g, DARK.b);
      doc.rect(0, 0, pw, ph, 'F');

      // Accent bar at top
      doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
      doc.rect(0, 0, pw, 4, 'F');

      // Brand name
      doc.setFontSize(14);
      doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
      doc.setFont('helvetica', 'bold');
      doc.text('NEXUS', 14, 25);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
      doc.text('Event Intelligence Platform', 40, 25);

      // Decorative line
      doc.setDrawColor(50, 50, 60);
      doc.setLineWidth(0.3);
      doc.line(14, 32, pw - 14, 32);

      // Main title
      const eventName = event.name || 'Event Brief';
      doc.setFontSize(32);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
      const titleLines = doc.splitTextToSize(eventName, pw - 28);
      doc.text(titleLines, 14, 60);
      y = 60 + (titleLines.length * 14);

      // Subtitle
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
      doc.text('Comprehensive Event Brief', 14, y + 5);
      y += 20;

      // Meta info boxes
      doc.setFillColor(30, 30, 40);
      doc.roundedRect(14, y, (pw - 35) / 2, 22, 3, 3, 'F');
      doc.roundedRect(14 + (pw - 35) / 2 + 7, y, (pw - 35) / 2, 22, 3, 3, 'F');

      doc.setFontSize(8);
      doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
      doc.text('VENUE', 20, y + 8);
      doc.text('DURATION', 20 + (pw - 35) / 2 + 7, y + 8);

      doc.setFontSize(11);
      doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
      doc.setFont('helvetica', 'bold');
      doc.text(event.venue || 'TBD', 20, y + 16);
      doc.text(`${event.days || 1} Day${(event.days || 1) > 1 ? 's' : ''}`, 20 + (pw - 35) / 2 + 7, y + 16);
      y += 32;

      // Second row of meta
      doc.setFillColor(30, 30, 40);
      doc.roundedRect(14, y, (pw - 35) / 2, 22, 3, 3, 'F');
      doc.roundedRect(14 + (pw - 35) / 2 + 7, y, (pw - 35) / 2, 22, 3, 3, 'F');

      doc.setFontSize(8);
      doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
      doc.text('EXPECTED ATTENDEES', 20, y + 8);
      doc.text('SESSIONS', 20 + (pw - 35) / 2 + 7, y + 8);

      doc.setFontSize(11);
      doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
      doc.setFont('helvetica', 'bold');
      doc.text(`${event.attendees || participantList.length || 'TBD'}`, 20, y + 16);
      doc.text(`${sessionList.length}`, 20 + (pw - 35) / 2 + 7, y + 16);
      y += 32;

      // Date info
      if (event.start_date || event.end_date) {
        doc.setFillColor(30, 30, 40);
        doc.roundedRect(14, y, pw - 28, 22, 3, 3, 'F');
        doc.setFontSize(8);
        doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
        doc.text('EVENT DATES', 20, y + 8);
        doc.setFontSize(11);
        doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
        doc.setFont('helvetica', 'bold');
        const d1 = formatDate(event.start_date);
        const d2 = formatDate(event.end_date);
        const dateStr = d1 === d2 ? d1 : `${d1} - ${d2}`;
        doc.text(dateStr, 20, y + 16);
        y += 32;
      }

      // Footer on cover
      doc.setFontSize(8);
      doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated: ${formatTimeNow()}`, 14, ph - 15);
      doc.text('Powered by NEXUS AI | Confidential', 14, ph - 10);

      // ════════════════════════════════════════════
      // PAGE 2+: SCHEDULE
      // ════════════════════════════════════════════
      if (includeSchedule && sessionList.length > 0) {
        setProgress('Adding schedule...');
        addContentPage();
        y = 20;

        // Section header
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
        doc.text('Schedule Overview', 14, y);
        y += 3;
        doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
        doc.setLineWidth(0.8);
        doc.line(14, y, 80, y);
        y += 8;

        doc.setFontSize(9);
        doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
        doc.setFont('helvetica', 'normal');
        doc.text(`${sessionList.length} sessions across ${event.days || 1} day(s)`, 14, y);
        y += 10;

        // Group by day
        const days = {};
        sessionList.forEach(s => {
          const d = s.day || 1;
          if (!days[d]) days[d] = [];
          days[d].push(s);
        });

        Object.keys(days).sort((a, b) => a - b).forEach(day => {
          const daySessions = days[day].sort((a, b) => (a.start_time || '').localeCompare(b.start_time || ''));

          // Check if we need a new page
          if (y > ph - 60) { addContentPage(); y = 20; }

          doc.setFontSize(12);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
          doc.text(`Day ${day}`, 14, y);
          y += 6;

          autoTable(doc, {
            startY: y,
            head: [['Time', 'Session', 'Speaker', 'Venue', 'Type']],
            body: daySessions.map(s => [
              `${s.start_time || ''} - ${s.end_time || ''}`,
              s.title || 'Untitled',
              s.speaker || '—',
              s.venue || '—',
              (s.session_type || 'talk').charAt(0).toUpperCase() + (s.session_type || 'talk').slice(1),
            ]),
            theme: 'grid',
            styles: {
              fontSize: 8,
              cellPadding: 3,
              textColor: [200, 200, 210],
              lineColor: [50, 50, 60],
              lineWidth: 0.2,
              fillColor: [22, 22, 32],
            },
            headStyles: {
              fillColor: [BRAND.r, BRAND.g, BRAND.b],
              textColor: [255, 255, 255],
              fontStyle: 'bold',
              fontSize: 8,
            },
            alternateRowStyles: {
              fillColor: [28, 28, 38],
            },
            margin: { left: 14, right: 14 },
          });

          y = doc.lastAutoTable.finalY + 10;
        });
      }

      // ════════════════════════════════════════════
      // PARTICIPANTS
      // ════════════════════════════════════════════
      if (includeParticipants && participantList.length > 0) {
        setProgress('Adding participant summary...');
        addContentPage();
        y = 20;

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
        doc.text('Participant Summary', 14, y);
        y += 3;
        doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
        doc.setLineWidth(0.8);
        doc.line(14, y, 85, y);
        y += 10;

        // Key metrics
        const totalParticipants = participantList.length;
        const orgs = new Set(participantList.map(p => p.organization || p.company).filter(Boolean));
        const roles = {};
        participantList.forEach(p => {
          const r = p.role || p.track || 'General';
          roles[r] = (roles[r] || 0) + 1;
        });

        // KPI boxes
        const kpis = [
          { label: 'Total Participants', value: totalParticipants.toString() },
          { label: 'Organizations', value: orgs.size.toString() },
          { label: 'Unique Roles/Tracks', value: Object.keys(roles).length.toString() },
        ];
        const boxW = (pw - 28 - 14) / 3;
        kpis.forEach((kpi, i) => {
          const bx = 14 + i * (boxW + 7);
          doc.setFillColor(30, 30, 40);
          doc.roundedRect(bx, y, boxW, 20, 2, 2, 'F');
          doc.setFontSize(7);
          doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
          doc.text(kpi.label.toUpperCase(), bx + 5, y + 7);
          doc.setFontSize(14);
          doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
          doc.setFont('helvetica', 'bold');
          doc.text(kpi.value, bx + 5, y + 16);
        });
        y += 30;

        // Role/Track breakdown table
        if (Object.keys(roles).length > 0) {
          doc.setFontSize(11);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
          doc.text('Breakdown by Role / Track', 14, y);
          y += 6;

          autoTable(doc, {
            startY: y,
            head: [['Role / Track', 'Count', '% of Total']],
            body: Object.entries(roles).sort((a, b) => b[1] - a[1]).map(([role, count]) => [
              role,
              count.toString(),
              `${((count / totalParticipants) * 100).toFixed(1)}%`,
            ]),
            theme: 'grid',
            styles: { fontSize: 8, cellPadding: 3, textColor: [200, 200, 210], lineColor: [50, 50, 60], lineWidth: 0.2, fillColor: [22, 22, 32] },
            headStyles: { fillColor: [BRAND.r, BRAND.g, BRAND.b], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
            alternateRowStyles: { fillColor: [28, 28, 38] },
            margin: { left: 14, right: 14 },
          });
          y = doc.lastAutoTable.finalY + 10;
        }

        // Top organizations
        if (orgs.size > 0) {
          if (y > ph - 60) { addContentPage(); y = 20; }
          const orgCounts = {};
          participantList.forEach(p => {
            const o = p.organization || p.company || '';
            if (o) orgCounts[o] = (orgCounts[o] || 0) + 1;
          });
          const topOrgs = Object.entries(orgCounts).sort((a, b) => b[1] - a[1]).slice(0, 15);

          doc.setFontSize(11);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(WHITE.r, WHITE.g, WHITE.b);
          doc.text('Top Organizations', 14, y);
          y += 6;

          autoTable(doc, {
            startY: y,
            head: [['Organization', 'Participants']],
            body: topOrgs.map(([org, count]) => [org, count.toString()]),
            theme: 'grid',
            styles: { fontSize: 8, cellPadding: 3, textColor: [200, 200, 210], lineColor: [50, 50, 60], lineWidth: 0.2, fillColor: [22, 22, 32] },
            headStyles: { fillColor: [BRAND.r, BRAND.g, BRAND.b], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
            alternateRowStyles: { fillColor: [28, 28, 38] },
            margin: { left: 14, right: 14 },
          });
        }
      }

      // ════════════════════════════════════════════
      // ACTIVITY LOG
      // ════════════════════════════════════════════
      if (includeActivity && activities.length > 0) {
        setProgress('Adding activity log...');
        addContentPage();
        y = 20;

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
        doc.text('Agent Activity Log', 14, y);
        y += 3;
        doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
        doc.setLineWidth(0.8);
        doc.line(14, y, 80, y);
        y += 10;

        doc.setFontSize(9);
        doc.setTextColor(GRAY.r, GRAY.g, GRAY.b);
        doc.setFont('helvetica', 'normal');
        doc.text(`${activities.length} recorded actions from the AI swarm`, 14, y);
        y += 8;

        const recentActivities = activities.slice(0, 30);
        autoTable(doc, {
          startY: y,
          head: [['Time', 'Agent', 'Action', 'Details']],
          body: recentActivities.map(a => {
            const time = a.timestamp ? new Date(a.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '';
            const agent = (a.agent || 'system').charAt(0).toUpperCase() + (a.agent || 'system').slice(1);
            const action = (a.action || '').replace(/_/g, ' ');
            const details = (a.details || '').substring(0, 80);
            return [time, agent, action, details];
          }),
          theme: 'grid',
          styles: { fontSize: 7, cellPadding: 2.5, textColor: [200, 200, 210], lineColor: [50, 50, 60], lineWidth: 0.2, fillColor: [22, 22, 32], overflow: 'ellipsize' },
          headStyles: { fillColor: [BRAND.r, BRAND.g, BRAND.b], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7 },
          alternateRowStyles: { fillColor: [28, 28, 38] },
          columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: 22 }, 2: { cellWidth: 35 }, 3: { cellWidth: 'auto' } },
          margin: { left: 14, right: 14 },
        });
      }

      // ── Add footers to all pages ──
      addFooter();

      // ── Step 3: Download ──
      setProgress('Downloading...');
      const dateSuffix = new Date().toISOString().split('T')[0];
      const fileName = `${(event.name || 'Event').replace(/\s+/g, '_')}_Brief_${dateSuffix}.pdf`;
      doc.save(fileName);

      setDone(true);
      setProgress('');
    } catch (err) {
      console.error('PDF generation failed:', err);
      setProgress(`Error: ${err.message}`);
    }
    setGenerating(false);
  };

  const sections = [
    { id: 'overview', icon: FileText, label: 'Event Overview', desc: 'Name, venue, dates, attendee count', color: 'text-primary', state: true, readOnly: true },
    { id: 'schedule', icon: Calendar, label: 'Schedule At-a-Glance', desc: 'Full day-by-day session grid', color: 'text-agents-chronos', state: includeSchedule, set: setIncludeSchedule },
    { id: 'participants', icon: Users, label: 'Participant Summary', desc: 'Breakdown by role, track & organization', color: 'text-agents-hermes', state: includeParticipants, set: setIncludeParticipants },
    { id: 'activity', icon: BarChart, label: 'Agent Activity Log', desc: 'Recent AI swarm actions & decisions', color: 'text-agents-athena', state: includeActivity, set: setIncludeActivity },
  ];

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4" onClick={onClose}>
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" />

      {/* Modal */}
      <div
        className="relative bg-card/95 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-fade-up"
        onClick={e => e.stopPropagation()}
      >
        {/* Header accent bar */}
        <div className="h-1 bg-gradient-to-r from-primary via-agents-chronos to-agents-hermes" />

        {/* Header */}
        <div className="p-6 pb-4 flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-primary/10 border border-primary/20">
              <FileText size={22} className="text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Export Event Brief</h2>
              <p className="text-xs text-gray-400 mt-0.5">Customize your comprehensive PDF report</p>
            </div>
          </div>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors p-1 rounded-lg hover:bg-white/5">
            <X size={20} />
          </button>
        </div>

        {/* Sections Selection */}
        <div className="px-6 pb-4 space-y-2">
          <p className="text-[10px] text-gray-400 uppercase font-bold tracking-wider mb-2">Select Included Sections</p>
          {sections.map(({ id, icon: Icon, label, desc, color, state, set, readOnly }) => (
            <div
              key={id}
              onClick={() => !readOnly && set(!state)}
              className={`flex items-center gap-3 bg-black/30 border ${state ? 'border-primary/50 bg-primary/5' : 'border-white/5 hover:border-white/10'} rounded-lg px-3 py-2.5 transition-colors ${readOnly ? 'opacity-90' : 'cursor-pointer'}`}
            >
              <div className={`p-1.5 rounded-lg ${state ? `bg-white/10 ${color}` : 'bg-white/5 text-gray-500'}`}>
                <Icon size={14} />
              </div>
              <div className="flex-1 min-w-0">
                <span className={`text-sm font-medium ${state ? 'text-white' : 'text-gray-400'} block transition-colors`}>{label}</span>
                <span className="text-[10px] text-gray-500">{desc}</span>
              </div>
              
              {/* Toggle switch visual or Lock */}
              {readOnly ? (
                <Lock size={14} className="text-gray-500 mr-1" />
              ) : (
                <div className={`w-8 h-4 rounded-full flex items-center transition-colors ${state ? 'bg-primary' : 'bg-gray-700'}`}>
                  <div className={`w-3 h-3 rounded-full bg-white shadow-sm transform transition-transform ${state ? 'translate-x-[18px]' : 'translate-x-0.5'}`} />
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Progress / Status */}
        {(generating || progress) && (
          <div className="mx-6 mb-3 bg-black/40 border border-white/5 rounded-lg px-4 py-3 flex items-center gap-3">
            {generating && !done && <Loader2 size={16} className="animate-spin text-primary flex-shrink-0" />}
            {done && <CheckCircle size={16} className="text-success flex-shrink-0" />}
            <span className={`text-sm ${done ? 'text-success' : 'text-gray-300'}`}>
              {done ? 'PDF downloaded successfully!' : progress}
            </span>
          </div>
        )}

        {/* Actions */}
        <div className="p-6 pt-3 border-t border-white/5 flex gap-3">
          <button
            onClick={onClose}
            className="flex-1 py-2.5 rounded-lg border border-white/10 text-gray-400 hover:text-white hover:bg-white/5 transition-colors text-sm font-medium"
          >
            Cancel
          </button>
          <button
            onClick={generatePDF}
            disabled={generating}
            className="flex-1 py-2.5 rounded-lg bg-primary hover:bg-primary/80 text-white transition-colors text-sm font-bold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-primary/25"
          >
            {generating ? (
              <><Loader2 size={16} className="animate-spin" /> Generating...</>
            ) : done ? (
              <><CheckCircle size={16} /> Download Again</>
            ) : (
              <><Download size={16} /> Generate & Download</>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default EventBriefModal;
